import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav>
          <a href="/">Home</a> <a href="/students">Students</a> <a href="/teachers">Teachers</a> <a href="/subjects">Subjects</a> <a href="/groups">Groups</a> <a href="/activities">Activities</a> <a href="/studentGroups">Student Groups</a> <a href="/reports">Reports</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
